name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_release:
    name: "Create flatpak release"
    runs-on:  ubuntu-24.04

    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Linux Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: flatfab.flatpak
          manifest-path: flatpak/edu.toronto.dgp.FlatFab.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Linux artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flatfab.flatpak
          asset_name: flatfab.flatpak
          asset_content_type: application/vnd.flatpak
