name: Linux Compilation

on:
  push:
    branches:
      - 'master'
      - 'continuous-integration'
      - 'cross-platform'
    tags:
      - 'v*'
  pull_request:
    branches:
    - 'master'
    - 'continuous-integration'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2

jobs:
  build:
    runs-on:  ubuntu-24.04
    #runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      ${{ env.QT_VERSION }}
          setup-python: false

      - name: Install other dependencies
        run: /usr/bin/sudo apt-get install libglu1-mesa-dev libeigen3-dev
              
      - name: Create build directory
        run:  mkdir ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run:  |
              cmake ..
              make
              
